version: "3.3"

services:
networks:
  medianet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
  monitoring:

services:
  transmission:
    image: haugene/transmission-openvpn:latest
    container_name: transmission
    restart: always
    volumes:
      - /nfs/pool/downloads:/data
    environment:
      - LOCAL_NETWORK=${LOCAL_NETWORK}
      - OPENVPN_PROVIDER=${OPENVPN_PROVIDER}
      - OPENVPN_USERNAME=${OPENVPN_USERNAME}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - PUID=${PUID}
      - PGID=${PGID}
    ports:
      - 9091:9091
    cap_add:
      - net_admin
    networks:
      - medianet

  calibre:
    image:  linuxserver/calibre:latest
    container_name: calibre
    restart: always
    volumes:
      - /nfs/pool/media/books:/books
      - /pool/calibre/calibre:/config
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - umask_set=022
    ports:
      - 3389:3389
      - 8080:8080

  lidarr:
    image: linuxserver/lidarr:latest
    container_name: lidarr
    restart: always
    volumes:
      - /nfs/pool/downloads/completed:/downloads
      - /pool/lidarr:/config
      - /nfs/pool/media/music:/music
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - 8686:8686
    networks:
      - medianet

  radarr:
    image: mdhiggins/radarr-sma
    container_name: radarr
    restart: always
    volumes:
      - /pool/radarr:/config
      - /pool/radarr/sma:/usr/local/sma/config
      - /nfs/pool/downloads/completed:/downloads
      - /nfs/pool/media/movies:/movies
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - 7878:7878
    networks:
      - medianet

  readarr:
    image: hotio/readarr:nightly
    container_name: readarr
    restart: always
    volumes:
      - /nfs/pool/media/books:/books
      - /nfs/pool/downloads/completed:/downloads
      - /pool/readarr:/config
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - 8787:8787
    networks:
      - medianet

  sonarr:
    image: mdhiggins/sonarr-sma
    container_name: sonarr
    restart: always
    volumes:
      - /pool/sonarr:/config
      - /pool/sonarr/sma:/usr/local/config/sma
      - /nfs/pool/media/tv:/tv
      - /nfs/pool/downloads/completed:/downloads
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - 8989:8989
    networks:
      - medianet

  bazarr:
    image: ghcr.io/linuxserver/bazarr
    container_name: bazarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /pool/bazarr/config:/config
      - /nfs/pool/media/movies:/movies
      - /nfs/pool/media/tv:/tv
    ports:
      - 6767:6767
    restart: unless-stopped
    networks:
      - medianet

  tautulli:
    image: linuxserver/tautulli:latest
    container_name: tautulli
    restart: always
    volumes:
      - /pool/tautulli:/config
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - 8181:8181
    networks:
      - medianet

  nzbget:
    image: ghcr.io/linuxserver/nzbget
    container_name: nzbget
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /pool/nzbget:/config
      - /nfs/pool/downloads:/downloads
    ports:
      - 6789:6789
    restart: unless-stopped
    networks:
      - medianet


  wireguard:
    image: ghcr.io/linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - TZ=${TZ}
      - SERVERURL=lukesturgis.synology.me
      - SERVERPORT=51820 #optional
      - PEERS=1 #optional
      - PEERDNS=auto #optional
    volumes:
      - /pool/wireguard/config:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
    networks:
      - medianet

  overseerr:
    image: ghcr.io/linuxserver/overseerr
    container_name: overseerr
    environment:
      - TZ=${TZ}
    volumes:
      - /pool/overseerr/config:/config
    ports:
      - 44005:5055
    restart: unless-stopped
    networks:
      - medianet

  heimdall:
    image: ghcr.io/linuxserver/heimdall
    container_name: heimdall
    environment:
      - TZ=${TZ}
    volumes:
      - /pool/heimdall/config:/config
    ports:
      - 82:80
      - 444:443
    restart: unless-stopped

      #  minecraft:
      #image: itzg/minecraft-server
      #container_name: minecraft
      #ports:
      #- 25565:25565
      #- 25575:25575
      #environment:
      #- EULA="TRUE"
      #- MEMORY=6G
      #- WHITELIST=nourishablegecko
      #volumes:
      #- /pool/minecraft:/data
      #tty: true
      #stdin_open: true
      #restart: unless-stopped

  ytmdl:
    image: ghcr.io/deepjyoti30/ytmdl-web:latest
    container_name: ytmdl
    ports:
      - 8082:8082
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - 3000:3000
    networks:
      - monitoring
    volumes:
      - /pool/grafana:/var/lib/grafana

  influxdb:
    image: influxdb
    container_name: influxdb
    restart: always
    ports:
      - 8086:8086
    networks:
      - monitoring
    volumes:
      - /pool/influxdb:/var/lib/influxdb

  varken:
    hostname: varken
    container_name: varken
    image: boerderij/varken
    networks:
      - medianet
      - monitoring
    volumes:
      - /pool/varken:/config
    environment:
      - TZ=America/New_York
    depends_on:
      - influxdb
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    networks:
      - medianet
    container_name: prowlarr
    environment:
      - TZ=${TZ}
    volumes:
      - /pool/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  ddclient:
    image: lscr.io/linuxserver/ddclient
    container_name: ddclient
    environment:
      - TZ=${TZ}
    volumes:
      - /pool/ddclient:/config
    restart: unless-stopped

  dashy:
    image: lissy93/dashy
    container_name: dashy
    restart: unless-stopped
    ports:
      - 4000:80
    volumes:
      - /pool/dashy/conf.yml:/app/public/conf.yml
    networks:
      - medianet
      - monitoring

  nextcloud:
    image: lscr.io/linuxserver/nextcloud
    container_name: nextcloud
    environment:
      - TZ=${TZ}
    volumes:
      - /pool/nextcloud/config:/config
      - /pool/nextcloud/data:/data
    ports:
      - 443:443
    restart: unless-stopped

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "85:80/tcp"
    environment:
      TZ: ${TZ}
      WEBPASSWORD: ${PIHOLE_WEBPASSWORD}
    volumes:
      - /pool/pihole/etc:/etc/pihole
      - /pool/pihole/dnsmasq.d:/etc/dnsmasq.d
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

  organizr:
    container_name: organizr
    image: organizr/organizr
    ports:
      - '86:80'
    volumes:
      - /pool/organizr:/config

  netdata:
    image: netdata/netdata
    container_name: netdata
    ports:
      - 19999:19999
    restart: unless-stopped
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - netdataconfig:/etc/netdata
      - netdatalib:/var/lib/netdata
      - netdatacache:/var/cache/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
    environment:
      - NETDATA_CLAIM_TOKEN=${NETDATA_CLAIM_TOKEN}
      - NETDATA_CLAIM_URL=https://app.netdata.cloud
      - NETDATA_CLAIM_ROOMS=${NETDATA_CLAIM_ROOMS}
      - DISABLE_TELEMETRY=1

  guacd:
    image: lscr.io/linuxserver/guacd
    container_name: guacd
    ports:
      - 4822:4822
    restart: unless-stopped

volumes:
  netdataconfig:
  netdatalib:
  netdatacache:
